services:
  - type: web
    name: heart-disease-risk-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: MODEL_VERSION
        value: "1.0.0"
      - key: MLFLOW_TRACKING_URI
        value: "file:./mlruns"
      - key: MLFLOW_EXPERIMENT_NAME
        value: "heart-disease-risk-serving"
      - key: ENABLE_MLFLOW_LOGGING
        value: "true"
      - key: LOG_DB_PATH
        value: "/srv/data/monitoring.db"
      - key: ALLOWED_ORIGINS
        value: "*"
